# Generated by Django 5.1.3 on 2025-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artifical_intellengence')),
                ('link', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='#000000', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
