# Generated by Django 5.1.2 on 2026-07-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('marketing', '0002_alter_marketing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_translations', to='languages.language')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='marketing.marketing')),
            ],
            options={
                'unique_together': {('marketing', 'language')},
            },
        ),
    ]
