# Generated by Django 5.1.2 on 2026-07-31 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0002_alter_artificial_intelligence_image'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialIntelligenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('artificial_intelligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artificial_intelligence.artificial_intelligence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artificial_intelligence_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('artificial_intelligence', 'language')},
            },
        ),
    ]
