# Generated by Django 5.1.3 on 2025-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoes',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
