# Generated by Django 5.1.2 on 2026-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_block_remove_user_block_other'),
        ('states', '0002_district_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
