# Generated by Django 5.1.2 on 2026-07-23 04:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_delete_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='states'),
        ),
    ]
