# Generated by Django 5.1.2 on 2026-07-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('states', '0004_states_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='states.district')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('district', 'language')},
            },
        ),
        migrations.CreateModel(
            name='StateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_translations', to='languages.language')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='states.states')),
            ],
            options={
                'unique_together': {('state', 'language')},
            },
        ),
    ]
