# Generated by Django 5.1.2 on 2024-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
