# Generated by Django 5.1.2 on 2026-07-31 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('news', '0002_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_translations', to='languages.language')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news')),
            ],
            options={
                'unique_together': {('news_item', 'language')},
            },
        ),
    ]
