# Generated by Django 5.1.2 on 2024-10-13 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupations', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categories')),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheme_type', models.IntegerField(choices=[(0, 'Central'), (1, 'State')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('dbt', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('income', models.IntegerField(default=0)),
                ('divyang', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField()),
                ('web_links', models.TextField(max_length=255)),
                ('mode_of_application', models.TextField(max_length=255)),
                ('occupations', models.CharField(max_length=255)),
                ('age_max', models.IntegerField()),
                ('age_min', models.IntegerField()),
                ('scheme_for', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('benificiaries', models.CharField(max_length=255)),
                ('religions', models.CharField(max_length=255)),
                ('casts', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_category', to='schemes.categories')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_category', to='states.states')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_Occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_occupation', to='occupations.occupations')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_occupations', to='schemes.schemes')),
            ],
        ),
    ]
