# Generated by Django 5.1.2 on 2024-12-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_category', to='states.states'),
        ),
    ]
