# Generated by Django 5.1.2 on 2024-12-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_scheme_areas_scheme_employements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemes',
            old_name='casts',
            new_name='castes',
        ),
    ]
