# Generated by Django 5.1.3 on 2025-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_rename_casts_schemes_castes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemes',
            old_name='income',
            new_name='income_max',
        ),
        migrations.AddField(
            model_name='schemes',
            name='income_min',
            field=models.IntegerField(default=0),
        ),
    ]
