# Generated by Django 5.1.3 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_rename_income_schemes_income_max_schemes_income_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='banner',
            field=models.ImageField(default='', upload_to='categories'),
        ),
    ]
