# Generated by Django 5.1.3 on 2025-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_categories_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='categories'),
        ),
    ]
