# Generated by Django 5.1.3 on 2025-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_alter_categories_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='schemes'),
        ),
    ]
