# Generated by Django 5.1.3 on 2025-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0008_schemes_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='business_related',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
