# Generated by Django 5.1.3 on 2025-02-14 14:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0009_schemes_business_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='schemes'),
        ),
    ]
