# Generated by Django 5.1.2 on 2026-07-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0010_alter_categories_banner_alter_categories_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='myscheme_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
