# Generated by Django 5.1.2 on 2026-07-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('schemes', '0011_schemes_myscheme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='schemes.categories')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SchemeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility', models.TextField(blank=True, default='')),
                ('required_documents', models.TextField(blank=True, default='')),
                ('mode_of_application', models.TextField(blank=True, default='')),
                ('occupations', models.CharField(blank=True, default='', max_length=255)),
                ('scheme_for', models.CharField(blank=True, default='', max_length=255)),
                ('marital_status', models.CharField(blank=True, default='', max_length=255)),
                ('benificiaries', models.CharField(blank=True, default='', max_length=255)),
                ('religions', models.CharField(blank=True, default='', max_length=255)),
                ('castes', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_translations', to='languages.language')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='schemes.schemes')),
            ],
            options={
                'unique_together': {('scheme', 'language')},
            },
        ),
    ]
