# Generated by Django 5.1.3 on 2025-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='business_plans')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('pdf', models.FileField(default='', upload_to='business_plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
