# Generated by Django 5.1.3 on 2025-02-14 14:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_plans', '0002_rename_businessplans_business_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plans',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='business_plans'),
        ),
    ]
