# Generated by Django 5.1.2 on 2026-07-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_plans', '0003_alter_business_plans_image'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='business_plans.business_plans')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('business_plan', 'language')},
            },
        ),
    ]
