"""
Django settings for SAHYOG_SETU_ADMIN project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '97ny&l)^z^6mxpt@%)qubngaexjiulj@628m*(5ng@cq9-#(j8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS=['127.0.0.1', '212.38.94.162', 'sahyogsetu.in', 'www.sahyogsetu.in']

# Same OAuth client the main React SPA already uses (see main.js) -- signing
# in with this ID on the quiz login page too is what makes it feel like one
# account instead of a second, unrelated login system.
GOOGLE_CLIENT_ID = '493480542408-tas10l37f73mankcbegv9bu2s0mlk4df.apps.googleusercontent.com'

CORS_ALLOW_CREDENTIALS = True
# ALL_ORIGINS + CREDENTIALS together let any website make authenticated
# (cookie-bearing) cross-origin requests and read the response -- restricted
# to the actual known origins instead (same-origin browser traffic doesn't
# need CORS at all; this only matters for the separate dev frontend / any
# future cross-origin caller).
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://sahyogsetu.in",
    "https://www.sahyogsetu.in",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]

# CORS_ALLOW_ALL_HEADERS = True

CORS_ALLOW_HEADERS = ["authorization", 'credentials', 'content-type']

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:3000', 'http://localhost:3000', 'https://sahyogsetu.in']

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# nginx terminates TLS and always forwards this header (see /etc/nginx/proxy_params)
# -- without it Django thinks every request is plain HTTP, which defeats the
# secure-cookie flags above and makes build_absolute_uri() emit http:// links.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'rest_framework',
    'apis',
    'news',
    'custom_admin',
    'occupations',
    'states',
    'schemes',
    'testimonials',
    'helplines',
    'banners',
    'important_documents',
    'important_portals',
    'scheme_announcements',
    'manage_gallery',
    'pages',
    'settings',
    'entrepreneurship.business_plans',
    'entrepreneurship.organization_registrations',
    'entrepreneurship.legal_registrations',
    'entrepreneurship.artificial_intelligence',
    'entrepreneurship.marketing',
    'quizzes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SAHYOG_SETU_ADMIN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SAHYOG_SETU_ADMIN.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME'   :'SAHYOG_SETU',
        'HOST'   : '127.0.0.1',
        'PORT'   : '3306',
        'USER'   : 'sahyog_setu_app',
        'PASSWORD' : '4pGFumUEox5H5p4HaIyr8DQaNp2F'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = ['accounts.EmailBackEnd.EmailBackEnd']

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/public/static/'
MEDIA_URL = "/media/"



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'public/static')]

# nginx serves /public/static/ directly via alias regardless of DEBUG -- this
# is only what `collectstatic` would write to, so it has to match that same
# directory (previously shadowed by a second, unconditional STATIC_ROOT
# assignment further down that pointed at a different, unused folder).
STATIC_ROOT = os.path.join(BASE_DIR, 'public/static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

