# Generated by Django 5.1.3 on 2025-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.ImageField(default='', upload_to='pages'),
        ),
    ]
