# Generated by Django 5.1.2 on 2026-07-31 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('scheme_announcements', '0002_alter_scheme_announcements_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeAnnouncementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_announcement_translations', to='languages.language')),
                ('scheme_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='scheme_announcements.scheme_announcements')),
            ],
            options={
                'unique_together': {('scheme_announcement', 'language')},
            },
        ),
    ]
