# Generated by Django 5.1.2 on 2026-08-01 09:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_announcements', '0003_schemeannouncementtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme_announcements',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[2000, 2000], upload_to='scheme_announcements'),
        ),
    ]
