# Generated by Django 5.1.3 on 2025-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2),
        ),
    ]
