# Generated by Django 5.1.2 on 2026-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_age_user_block_user_block_other_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='block_other',
        ),
    ]
