# Generated by Django 5.1.2 on 2026-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_block_remove_user_block_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
