# Generated by Django 5.1.3 on 2025-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legal_Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='important_documents')),
                ('banner', models.ImageField(blank=True, default='', null=True, upload_to='important_documents')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField()),
                ('web_links', models.TextField(max_length=255)),
                ('mode_of_application', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
