# Generated by Django 5.1.3 on 2025-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal_registrations',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='legal_registrations'),
        ),
        migrations.AlterField(
            model_name='legal_registrations',
            name='image',
            field=models.ImageField(default='', upload_to='legal_registrations'),
        ),
    ]
