# Generated by Django 5.1.2 on 2026-07-31 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('legal_registrations', '0003_alter_legal_registrations_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRegistrationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility', models.TextField(blank=True, default='')),
                ('required_documents', models.TextField(blank=True, default='')),
                ('mode_of_application', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_registration_translations', to='languages.language')),
                ('legal_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='legal_registrations.legal_registrations')),
            ],
            options={
                'unique_together': {('legal_registration', 'language')},
            },
        ),
    ]
