# Generated by Django 5.1.3 on 2025-01-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='important_portals',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='important_portals'),
        ),
    ]
