# Generated by Django 5.1.3 on 2025-02-14 14:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('important_portals', '0002_important_portals_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='important_portals',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='important_portals'),
        ),
        migrations.AlterField(
            model_name='important_portals',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='important_portals'),
        ),
    ]
