# Generated by Django 5.1.2 on 2026-07-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_portals', '0003_alter_important_portals_banner_and_more'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPortalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('mode_of_application', models.TextField(blank=True, default='')),
                ('important_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='important_portals.important_portals')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_portal_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('important_portal', 'language')},
            },
        ),
    ]
