# Generated by Django 5.1.3 on 2026-02-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('certificate_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/images')),
                ('logo_1', models.ImageField(upload_to='quiz/authorities/logos')),
                ('logo_2', models.ImageField(upload_to='quiz/authorities/logos')),
                ('authority1_name', models.CharField(max_length=255)),
                ('authority1_designation', models.CharField(max_length=255)),
                ('authority1_sign_image', models.ImageField(upload_to='quiz/authorities/signatures')),
                ('authority2_name', models.CharField(max_length=255)),
                ('authority2_designation', models.CharField(max_length=255)),
                ('authority2_sign_image', models.ImageField(upload_to='quiz/authorities/signatures')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('correct_option', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quizes')),
            ],
        ),
    ]
