# Generated by Django 6.0.2 on 2026-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_quizes_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='quizz_time',
            field=models.IntegerField(default=0),
        ),
    ]
