# Generated by Django 6.0.2 on 2026-02-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizzes_quizz_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='quizz_time',
            new_name='quiz_time',
        ),
    ]
