# Generated by Django 5.1.2 on 2026-07-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_rename_quizz_time_quizzes_quiz_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='leaderboard_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='one_attempt_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='pass_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='questions_per_attempt',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quizzes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_snapshot', models.TextField()),
                ('selected_option', models.CharField(max_length=10)),
                ('correct_option', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation_snapshot', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.questions')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizattempt')),
            ],
        ),
    ]
