# Generated by Django 5.1.2 on 2026-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_questions_explanation_quizzes_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_background',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/certificate_bg'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='name_top_pct',
            field=models.FloatField(default=42.0),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='score_top_pct',
            field=models.FloatField(default=64.0),
        ),
    ]
