# Generated by Django 5.1.2 on 2026-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quizattempt_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
