# Generated by Django 5.1.2 on 2026-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizattempt_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='source',
            field=models.CharField(db_index=True, default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
