# Generated by Django 5.1.2 on 2026-07-08 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quizattempt_source_quizzes_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_response_per_question'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('user', 'quiz'), name='one_live_attempt_per_user_quiz'),
        ),
    ]
