# Generated by Django 5.1.2 on 2026-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quizattempt_question_ids_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='one_live_attempt_per_user_quiz',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='live_lock',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
