# Generated by Django 5.1.2 on 2026-07-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_quizattempt_one_live_attempt_per_user_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('option_1', models.CharField(blank=True, default='', max_length=255)),
                ('option_2', models.CharField(blank=True, default='', max_length=255)),
                ('option_3', models.CharField(blank=True, default='', max_length=255)),
                ('option_4', models.CharField(blank=True, default='', max_length=255)),
                ('explanation', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_translations', to='quizzes.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.questions')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuizTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_translations', to='quizzes.language')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.quizzes')),
            ],
            options={
                'unique_together': {('quiz', 'language')},
            },
        ),
    ]
