# Generated by Django 5.1.2 on 2026-07-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_language_quizattempt_language_questiontranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
