# Generated by Django 5.1.2 on 2026-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_questionresponse_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='certificate_accent_color',
            field=models.CharField(default='#C8A951', max_length=7),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_name_color',
            field=models.CharField(default='#1B4332', max_length=7),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_paper_color',
            field=models.CharField(default='#FAF8EF', max_length=7),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_pattern',
            field=models.CharField(choices=[('classic', 'Classic (guilloche + medallion)'), ('plain', 'Plain (solid color, no pattern)')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='logo1_x_pct',
            field=models.FloatField(default=14.0),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='logo1_y_pct',
            field=models.FloatField(default=11.0),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='logo2_x_pct',
            field=models.FloatField(default=86.0),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='logo2_y_pct',
            field=models.FloatField(default=11.0),
        ),
    ]
