# Generated by Django 5.1.2 on 2026-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quizzes_certificate_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='certificate_border_style',
            field=models.CharField(choices=[('triple', 'Triple line (classic)'), ('double', 'Double line'), ('single', 'Single line')], default='triple', max_length=10),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_corners_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_name_font',
            field=models.CharField(choices=[('script', 'Script (cursive)'), ('serif', 'Elegant serif'), ('bold', 'Bold serif')], default='script', max_length=10),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='certificate_title_color',
            field=models.CharField(default='#111111', max_length=7),
        ),
    ]
