# Generated by Django 5.1.3 on 2025-01-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Important_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'In Active'), (1, 'Active')], default=0)),
                ('dbt', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('income', models.IntegerField(default=0)),
                ('divyang', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField()),
                ('web_links', models.TextField(max_length=255)),
                ('mode_of_application', models.TextField(max_length=255)),
                ('occupations', models.CharField(max_length=255)),
                ('age_max', models.IntegerField()),
                ('age_min', models.IntegerField()),
                ('scheme_for', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('benificiaries', models.CharField(max_length=255)),
                ('religions', models.CharField(max_length=255)),
                ('castes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Important_Document_Occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_document_occupation', to='occupations.occupations')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_document_occupations', to='important_documents.important_documents')),
            ],
        ),
        migrations.CreateModel(
            name='Important_Document_Employements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_document_employment', to='important_documents.important_documents')),
            ],
        ),
        migrations.CreateModel(
            name='Important_Document_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_document_areas', to='important_documents.important_documents')),
            ],
        ),
    ]
