# Generated by Django 5.1.3 on 2025-01-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('important_documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='important_document_areas',
            old_name='scheme',
            new_name='important_document',
        ),
        migrations.RenameField(
            model_name='important_document_employements',
            old_name='scheme',
            new_name='important_document',
        ),
        migrations.RenameField(
            model_name='important_document_occupations',
            old_name='scheme',
            new_name='important_document',
        ),
    ]
