# Generated by Django 5.1.3 on 2025-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_documents', '0002_rename_scheme_important_document_areas_important_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='important_documents',
            name='image',
            field=models.ImageField(default='', upload_to='important_documents'),
        ),
    ]
