# Generated by Django 5.1.3 on 2025-01-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('important_documents', '0003_important_documents_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='important_document_employements',
            name='important_document',
        ),
        migrations.RemoveField(
            model_name='important_document_occupations',
            name='important_document',
        ),
        migrations.RemoveField(
            model_name='important_document_occupations',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='benificiaries',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='castes',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='dbt',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='divyang',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='income',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='occupations',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='religions',
        ),
        migrations.RemoveField(
            model_name='important_documents',
            name='scheme_for',
        ),
        migrations.DeleteModel(
            name='Important_Document_Areas',
        ),
        migrations.DeleteModel(
            name='Important_Document_Employements',
        ),
        migrations.DeleteModel(
            name='Important_Document_Occupations',
        ),
    ]
