# Generated by Django 5.1.3 on 2025-01-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_documents', '0004_remove_important_document_employements_important_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='important_documents',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='important_documents'),
        ),
    ]
