# Generated by Django 5.1.2 on 2026-07-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_documents', '0006_alter_important_documents_banner_and_more'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDocumentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility', models.TextField(blank=True, default='')),
                ('required_documents', models.TextField(blank=True, default='')),
                ('mode_of_application', models.TextField(blank=True, default='')),
                ('important_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='important_documents.important_documents')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_document_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('important_document', 'language')},
            },
        ),
    ]
