# Generated by Django 5.1.3 on 2025-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization_registration',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='organization_registration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization_registration',
            name='mode_of_application',
        ),
        migrations.AddField(
            model_name='organization_registration',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
