# Generated by Django 5.1.3 on 2025-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_registrations', '0002_remove_organization_registration_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization_registration',
            name='link',
        ),
        migrations.AddField(
            model_name='organization_registration',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='organization_registrations'),
        ),
        migrations.AddField(
            model_name='organization_registration',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organization_registration',
            name='mode_of_application',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization_registration',
            name='image',
            field=models.ImageField(default='', upload_to='organization_registrations'),
        ),
    ]
