# Generated by Django 5.1.3 on 2025-02-14 14:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_registrations', '0003_remove_organization_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_registration',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='organization_registrations'),
        ),
        migrations.AlterField(
            model_name='organization_registration',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='organization_registrations'),
        ),
    ]
