# Generated by Django 5.1.2 on 2025-05-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_registrations', '0004_alter_organization_registration_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_registration',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='organization_registrations'),
        ),
    ]
