# Generated by Django 5.1.2 on 2026-07-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('organization_registrations', '0005_organization_registration_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegistrationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('mode_of_application', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_registration_translations', to='languages.language')),
                ('organization_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='organization_registrations.organization_registration')),
            ],
            options={
                'unique_together': {('organization_registration', 'language')},
            },
        ),
    ]
