# Generated by Django 5.1.3 on 2025-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helplines',
            name='color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='helplines',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
