# Generated by Django 5.1.3 on 2025-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0002_helplines_color_helplines_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helplines',
            name='image',
            field=models.ImageField(upload_to='helplines'),
        ),
    ]
