# Generated by Django 5.1.3 on 2025-01-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0003_alter_helplines_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helplines',
            old_name='helpline_number',
            new_name='link',
        ),
    ]
