# Generated by Django 5.1.2 on 2026-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0005_alter_helplines_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='helplines',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
