# Generated by Django 5.1.2 on 2026-07-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helplines', '0006_helplines_number'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelplineTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='helplines.helplines')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpline_translations', to='languages.language')),
            ],
            options={
                'unique_together': {('helpline', 'language')},
            },
        ),
    ]
