# Generated by Django 5.1.2 on 2026-07-31 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_translations', to='languages.language')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='occupations.occupations')),
            ],
            options={
                'unique_together': {('occupation', 'language')},
            },
        ),
    ]
